#!/bin/bash
#
# https://docs.aws.amazon.com/lambda/latest/dg/runtimes-walkthrough.html
#
set -euo pipefail

# Initialization - load function handler
source $LAMBDA_TASK_ROOT/"$(echo $_HANDLER | cut -d. -f1).sh"

# Processing
while true; do
  HEADERS="$(mktemp)"
  # Get an event
  EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
  REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

  cat<<EOF
LAMBDA_TASK_ROOT:       ${LAMBDA_TASK_ROOT}
AWS_LAMBDA_RUNTIME_API: ${AWS_LAMBDA_RUNTIME_API}
_HANDLER:               ${_HANDLER}
REQUEST_ID:             ${REQUEST_ID}
HEADERS:                ${HEADERS}
EOF

  # Execute the handler function from the script
  echo "---- start evaluating the handler. ----"
  RESPONSE=$($(echo "$_HANDLER" | cut -d. -f2) "$EVENT_DATA")
  echo "---- end evaluating the handler. ----"

  # Send the response
  curl -s -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response" -d "$RESPONSE"
done
